package com.tempestsoul.dnd.d20;


public enum CreatureType {
	ABERRATION, ANIMAL, CONSTRUCT, OOZE, ELEMENTAL, OUTSIDER, HUMANOID, DRAGON, FEY,
	GIANT, MAGICAL_BEAST, MONSTROUS_HUMANOID, PLANT, UNDEAD, VERMIN;
}
